models/Album.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;
use app\models\Photo;

/**
 * Class Album
 * @package app\models
 */
class Album extends ActiveRecord
{

    public function rules()
    {
        return [
            [
                [
                    'name',
                    'description',
                    'photographer',
                ],
                'required'
            ],
            ['email', 'email'],
        ];
    }

    /**
     * @param null $id
     * @return array
     */
    static function getIdName($id = null)
    {
        $albums = $id ? self::findOne($id) : self::find()->all();
        $result = [];
        if (is_array($albums)) {
            foreach ($albums as $album) {
                $result[$album->id] = $album->name;
            }
        } elseif ($albums instanceof self) {
            $result[$albums->id] = $albums->name;
        }
        return $result;
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getPhotos()
    {
        return Photo::find()->where(['albumId' => $this->id])->orderBy('createDateTime DESC')->all();
    }

    /**
     * @return int
     */
    public function getCountPhotos()
    {
        return count($this->getPhotos());
    }

    /**
     * @return int
     */
    public function getLastPhoto()
    {
        $photo = null;
        if ($this->getPhotos()) {
            $photo = $this->getPhotos()[0];
        }
        return $photo;
    }
}

controllers/AlbumController.php
<?php

namespace app\controllers;

use app\models\Photo;
use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Album as ModelAlbum;

/**
 * Class TestController
 * @package app\controllers
 */
class AlbumController extends Controller
{
    /**
     * Таблица альбомов
     * @return string
     */
    public function actionIndex()
    {

        $query = ModelAlbum::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $modelAlbum = $query->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();


        return $this->render('index', [
            'model' => $modelAlbum,
            'pagination' => $pagination,
        ]);
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $view = 'create';

        $model = new modelAlbum();

        if ($model->load($request->post()) && $model->validate()) {
            $model->createDateTime = (new \DateTime())->format('Y:m:d h:i:s');
            $model->editDateTime = (new \DateTime())->format('Y:m:d h:i:s');
            $model->save();
            $view = 'createDone';
        }

        return $this->render($view, [
            'model' => $model
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $view = 'delete';

        /** @var ModelAlbum $album */
        $album = ModelAlbum::findOne($id);

        if ($album->load($request->post()) && $album->validate()) {
            $photoAlbum = $request->post();
            if ($photoAlbum['Album']['id'] == $id) {
                /** @var Photo $photo */
                foreach($album->getPhotos() as $photo) {
                    $photo->delete();
                }
                $album->delete();
                $view = 'deleteDone';
            } else {
                throw new \Exception('Не верный параметр');
            }
        }

        return $this->render($view, [
            'album' => $album
        ]);
    }

    /**
     * @return string
     */
    public function actionEdit($id)
    {
        $request = Yii::$app->request;
        $view = 'edit';

        /** @var ModelAlbum $model */
        $model = ModelAlbum::findOne($id);

        if ($model->load($request->post()) && $model->validate()) {
            $model->editDateTime = (new \DateTime())->format('Y:m:d h:i:s');
            $model->save();
            $view = 'editDone';
        }

        return $this->render($view, [
            'model' => $model
        ]);
    }


    public function actionView($id)
    {
        /** @var ModelAlbum $model */
        $model = ModelAlbum::findOne($id);

        return $this->render('view', [
            'model' => $model
        ]);
    }
}

controllers/PhotoController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\UploadForm;
use app\models\Photo;
use app\models\Album;
use yii\web\UploadedFile;

/**
 * Class TestController
 * @package app\controllers
 */
class PhotoController extends Controller
{

    public function actionIndex()
    {
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $options = Album::getIdName($request->get('albumId'));
        $uploadForm = new UploadForm();
        $photo = new Photo();
        $view = 'create';

        if (Yii::$app->request->isPost) {
            $uploadForm->imageFile = UploadedFile::getInstance($uploadForm, 'imageFile');

            if ($uploadForm->upload()) {
                $photo->imageFile = $uploadForm->imageFile;
                $photoPost = $request->post('Photo');
                $photo->title = $photoPost['title'];
                $photo->address = $photoPost['address'];
                $photo->albumId =  $photoPost['albumId'];
                $photo->createDateTime = (new \DateTime())->format('Y:m:d h:i:s');
                $photo->editDateTime = (new \DateTime())->format('Y:m:d h:i:s');
                $photo->save();
                $view = 'createDone';
            }
        }
        return $this->render($view, [
            'model' => $uploadForm,
            'photo' => $photo,
            'options' => $options,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionEdit($id)
    {
        $request = Yii::$app->request;
        $options = Album::getIdName($request->get('albumId'));

        $photo = Photo::findOne($id);
        $view = 'edit';

        if (Yii::$app->request->isPost) {
            $photoPost = $request->post('Photo');

            $photo->title = $photoPost['title'];
            $photo->address = $photoPost['address'];
            $photo->editDateTime = (new \DateTime())->format('Y:m:d h:i:s');
            $photo->save();

            $view = 'editDone';
        }
        return $this->render($view, [
            'photo' => $photo,
            'options' => $options,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;

        $photo = Photo::findOne($id);
        $view = 'delete';

        if (Yii::$app->request->isPost) {
            $photoPost = $request->post();
            if ($photoPost['Photo']['id'] == $id) {
                $photo->delete();
                $view = 'deleteDone';
            } else {
                throw new \Exception('Не верный параметр');
            }
        }

        return $this->render($view, [
            'photo' => $photo,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $photo = Photo::findOne($id);
        return $this->render('view', [
            'photo' => $photo,
        ]);
    }
}

views/album/create.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;


$this->title = 'Создание альбома';
?>

<div class="site-index">
    <h1>Создание альбома</h1>
    <br />
    <div class="form-group-sm">
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->label('Название альбома') ?>

        <?= $form->field($model, 'description')->label('Описание альбома') ?>

        <?= $form->field($model, 'photographer')->label('Имя фотографа') ?>

        <?= $form->field($model, 'email')->label('Адрес эл. почты') ?>

        <?= $form->field($model, 'phone')->label('Контактный телефон') ?>

        <div class="form-group">
            <?= Html::submitButton('создать', ['class' => 'btn btn-primary']) ?>
            <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">вернуться</a>
        </div>

        <?php ActiveForm::end(); ?>


    </div>
</div>

views/album/createDone.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Создание альбома';
?>

<div class="site-index">
    <h1>Создание альбома</h1>
    <br />
    Альбом <span class="text-primary"><?php echo $model->name; ?></span> успешно создан.
    <br />
    <br />
    <div class="form-group">
        <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album\create']); ?>">создать еще</a>
        <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">к списку альбомов</a>
    </div>

    </div>
</div>

views/album/delete.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Photo;
use app\models\Album;


/** @var Photo $photo */
/** @var Album $album */

?>
<div class="site-index">
    <h1>Удаление альбома</h1>
    <div class="form-group-sm">
        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
            <p>Вы действительно хотите удалить альбом <span class="text-primary"><?php echo $album->name; ?></span></p>

            <?php  echo $form->field($album, 'id')->hiddenInput()->label(false); ?>

            <div class="form-group">
                <?= Html::submitButton('удалить', ['class' => 'btn btn-primary']) ?>
                <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">вернуться</a>
            </div>
        <?php ActiveForm::end() ?>
    </div>
</div>

views/album/deleteDone.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Photo;


/** @var  Photo $photo */

?>
<div class="site-index">
    <h1>Удаление альбома</h1>

        <p>Альбом успешно удалено.</p>
        <div class="form-group">
            <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">к списку альбомов</a>
        </div>
</div>

views/album/edit.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;


$this->title = 'Изменение альбома';
?>

<div class="site-index">
    <h1>Изменение альбома</h1>
    <br />
    <div class="form-group-sm">
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->label('Название альбома') ?>

        <?= $form->field($model, 'description')->label('Описание альбома') ?>

        <?= $form->field($model, 'photographer')->label('Имя фотографа') ?>

        <?= $form->field($model, 'email')->label('Адрес эл. почты') ?>

        <?= $form->field($model, 'phone')->label('Контактный телефон') ?>

        <div class="form-group">
            <?= Html::submitButton('изменить', ['class' => 'btn btn-primary']) ?>
            <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">вернуться</a>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

views/album/editDone.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Изменение альбома';
?>

<div class="site-index">
    <h1>Изменение альбома</h1>
    <br />
    Альбом <span class="text-primary"><?php echo $model->name; ?></span> успешно изменен.
    <br />
    <br />
    <div class="form-group">
        <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">к списку альбомов</a>
    </div>

    </div>
</div>

views/album/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\Album;

/** @var Album $album */

$this->title = 'Альбомы';
?>

<div class="site-index">
    <h1>Список альбомов</h1>
    <br />
    <div class="form-group">
        <a class="btn bg-info" href="<?php echo \Yii::$app->urlManager->createUrl(['album/create']); ?>">добавить новый альбом</a>
        <a class="btn bg-success" href="<?php echo \Yii::$app->urlManager->createUrl(['photo/create']); ?>">добавить фото</a>
    </div>

    <div class="greed">
        <table class="table">
            <tr>
                <td>Название</td>
                <td>Фотографий в альбоме</td>
                <td>Последнее добавленное фото</td>
                <td>Действия</td>
            </tr>
            <?php foreach ($model as $album): ?>
            <tr>
                <td>
                    <?= Html::encode("{$album->name}") ?>
                </td>
                <td>
                    <?= Html::encode("{$album->getCountPhotos()}") ?>
                </td>
                <td>
                    <?php $photo = $album->getLastPhoto();
                    if ($photo) {
                        echo "дата создания:". Html::encode("{$photo->createDateTime}");
                        echo "<br/>";
                        echo Html::img('/uploads/' . $photo->imageFile, ['class' => 'img-thumbnail', 'width'=>"100", 'height'=>"100"]);
                    }
                    ?>
                </td>
                <td>
                    <p><a class="btn" href="<?php echo \Yii::$app->urlManager->createUrl(["album/view", 'id' => $album->id]); ?>">просмотреть</a></p>
                    <p><a class="btn" href="<?php echo \Yii::$app->urlManager->createUrl(['album/edit', 'id' => $album->id]); ?>">редактировать</a></p>
                    <p><a class="btn" href="<?php echo \Yii::$app->urlManager->createUrl(['album/delete', 'id' => $album->id]); ?>">удалить</a></p>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?= LinkPager::widget(['pagination' => $pagination]) ?>
    </div>
</div>

views/album/view.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Photo;
use app\models\Album;

/** @var Photo $photo */

$this->title = 'Создание альбома';
?>

<div class="site-index">
    <h1>Просмотреть альбом</h1>
    <br />
    <div class="form-group-sm">

        <ul>
            <li><label>Название альбома: </label>: <?= Html::encode($model->name) ?></li>
            <li><label>Описание альбома: </label>: <?= Html::encode($model->description) ?></li>
            <li><label>Имя фотографа: </label>: <?= Html::encode($model->photographer) ?></li>
            <li><label>Адрес эл. почты: </label>: <?= Html::encode($model->email) ?></li>
            <li><label>Контактный телефон: </label>: <?= Html::encode($model->phone) ?></li>
        </ul>


        <div class="form-group">
            <a class="btn bg-success" href="<?php echo \Yii::$app->urlManager->createUrl(['photo/create', 'albumId' => $model->id]); ?>">Добавить фото</a>
            <a class="btn bg-primary" href="<?php echo \Yii::$app->urlManager->createUrl(['album']); ?>">вернуться</a>
        </div>
    </div>

    <?php
    /** @var Album $model */
    $photos = $model->getPhotos();

    if (count($photos) > 0) { ?>
        <div class="greed">
            <table class="table">
                <tr>
                    <td>Фотографя</td>
                    <td>Действия</td>
                </tr>
                <?php foreach ($photos as $photo): ?>
                    <tr>
                        <td>
                            название: <?= Html::encode("{$photo->title}") ?>
                            адрес: <?= Html::encode("{$photo->address}") ?>
                            дата создания: <?= Html::encode("{$photo->createDateTime}") ?>
                            <div class="img-thumbnail">
                            <?php echo $img = Html::img('/uploads/' . $photo->imageFile, ['class' => 'img-thumbnail']);?>
                            </div>
                        </td>
                        <td>
                            <p><a class="btn" href="<?php echo \Yii::$app->urlManager->createUrl(["photo/view", 'id' => $photo->id]); ?>">просмотреть</a></p>
                            <p><a class="btn" href="<?php echo \Yii::$app->urlManager->createUrl(["photo/edit", 'id' => $photo->id]); ?>">редактировать</a></p>
                            <p><a class="btn" href="<?php echo \Yii::$app->urlManager->createUrl(['photo/delete', 'id' => $photo->id]); ?>">удалить</a></p>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php } ?>
</div>